'use client';
import React, { useState, useEffect, Suspense } from 'react';
import axios from 'axios';
import { useSearchParams } from 'next/navigation';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3000';

const S = {
  page: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#050508', padding: '24px', position: 'relative' as const, overflow: 'hidden', fontFamily: "'Outfit', sans-serif" },
  orb: (w:any,h:any,r:any,t:any,l:any) => ({ position: 'absolute' as const, width: w, height: h, borderRadius: '50%', background: `radial-gradient(circle, ${r} 0%, transparent 70%)`, top: t, left: l, pointerEvents: 'none' as const }),
  card: { position: 'relative' as const, zIndex: 10, width: '100%', maxWidth: 460, background: 'rgba(12,10,24,0.85)', border: '1px solid rgba(124,58,237,0.18)', borderRadius: 24, padding: '48px 40px', backdropFilter: 'blur(30px)', boxShadow: '0 0 60px rgba(88,28,220,0.15)', textAlign: 'center' as const },
  title: { fontSize: 28, fontWeight: 800, letterSpacing: '-0.04em', color: '#e8e6ff', marginBottom: 8 },
  sub: { fontSize: 13, color: '#6b6b8a', lineHeight: 1.6, marginBottom: 32 },
  btn: (loading:boolean) => ({ width: '100%', padding: '16px', background: 'linear-gradient(135deg, #7c3aed 0%, #5b21b6 100%)', border: '1px solid rgba(168,85,247,0.4)', borderRadius: 14, color: '#fff', fontSize: 15, fontWeight: 700, fontFamily: "'Outfit', sans-serif", cursor: loading?'default':'pointer', boxShadow: '0 0 25px rgba(124,58,237,0.35)', opacity: loading?0.7:1 }),
  keyDisplay: { background: 'rgba(6,4,16,0.8)', border: '1px solid rgba(124,58,237,0.4)', borderRadius: 12, padding: '16px', fontFamily: "'JetBrains Mono', monospace", fontSize: 20, color: '#c4b5fd', letterSpacing: '2px', fontWeight: 600, marginTop: 16 }
};

function GatewayContent() {
  const searchParams = useSearchParams();
  const hwid = searchParams.get('hwid');
  const script_id = searchParams.get('script');
  
  const [step, setStep] = useState(0); // 0=start, 1=verifying, 2=done, 3=error
  const [keyData, setKeyData] = useState({ key: '', expires: '' });
  const [err, setErr] = useState('');

  const handleStart = () => {
    if (!hwid || !script_id) {
      setErr("Missing HWID or Script ID in URL. Check the link provided by your script.");
      setStep(3);
      return;
    }
    
    setStep(1);
    
    // Simulate Work.ink / Lootlabs checkpoint redirects
    setTimeout(async () => {
      try {
        const res = await axios.post(`${API_BASE_URL}/api/gateway/complete`, { script_id: script_id, hwid: hwid });
        if (res.data.success) {
          setKeyData({ key: res.data.key, expires: res.data.expires_at });
          setStep(2);
        } else {
          setErr(res.data.message);
          setStep(3);
        }
      } catch (error: any) {
        setErr(error.response?.data?.message || 'Gateway verification failed.');
        setStep(3);
      }
    }, 2000);
  };

  if (!hwid || !script_id) {
    return (
      <div style={S.card}>
        <div style={S.title}>Invalid Link</div>
        <div style={{...S.sub, color: '#fca5a5'}}>You must access this page via the URL generated by the Roblox script (it requires your unique HWID).</div>
      </div>
    );
  }

  return (
    <div style={S.card}>
      <div style={{ width: 64, height: 64, borderRadius: 20, background: 'rgba(124,58,237,0.1)', border: '1px solid rgba(124,58,237,0.3)', margin: '0 auto 24px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#a855f7" strokeWidth="2" strokeLinecap="round">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
        </svg>
      </div>

      {step === 0 && (
        <>
          <div style={S.title}>LuaGuard Gateway</div>
          <div style={S.sub}>Complete the verification steps below to generate your unique, time-limited script access key for HWID: <span style={{color: '#a855f7'}}>{hwid.slice(0,8)}…</span></div>
          <button onClick={handleStart} style={S.btn(false)}>Start Verification</button>
        </>
      )}

      {step === 1 && (
        <>
          <div style={S.title}>Verifying...</div>
          <div style={S.sub}>Simulating Work.ink / Lootlabs checkpoints. Please wait, do not close this page.</div>
          <button disabled style={S.btn(true)}>Processing Checkpoints…</button>
        </>
      )}

      {step === 2 && (
        <>
          <div style={S.title}>Verification Complete</div>
          <div style={S.sub}>Your key has been generated and bound to your device. It will expire on: <br/><strong style={{color:'#fff'}}>{new Date(keyData.expires).toLocaleString()}</strong></div>
          <div style={S.keyDisplay}>{keyData.key}</div>
          <div style={{ fontSize: 11, color: '#6b6b8a', marginTop: 16 }}>Copy this key and paste it into the script prompt.</div>
        </>
      )}

      {step === 3 && (
        <>
          <div style={S.title}>Verification Failed</div>
          <div style={{...S.sub, color: '#fca5a5'}}>{err}</div>
          <button onClick={() => { setStep(0); setErr(''); }} style={S.btn(false)}>Try Again</button>
        </>
      )}
    </div>
  );
}

export default function GetKeyPage() {
  return (
    <div style={S.page}>
      <div style={S.orb(500,500,'rgba(59,130,246,0.15)','10%','-10%')} />
      <div style={S.orb(600,600,'rgba(124,58,237,0.12)','40%','60%')} />
      <Suspense fallback={<div style={{color:'#fff'}}>Loading Gateway...</div>}>
        <GatewayContent />
      </Suspense>
    </div>
  );
}
